apiVersion: v1
kind: Service
metadata:
  name: hello-world-test-service-argo
spec:
  type: NodePort
  selector:
    greeting: hello
    version: one
  ports:
  - protocol: TCP
    port: 60000
    targetPort: 50000
